STRINGS = {
    'props.axis.x': {"ZH": '骨骼局部 X 轴（或四元数 X 分量）', "EN": 'Bone local X axis (or quaternion X component)'},
    'props.axis.y': {"ZH": '骨骼局部 Y 轴（或四元数 Y 分量）', "EN": 'Bone local Y axis (or quaternion Y component)'},
    'props.axis.z': {"ZH": '骨骼局部 Z 轴（或四元数 Z 分量）', "EN": 'Bone local Z axis (or quaternion Z component)'},
    'props.axis.w': {"ZH": '四元数 W 分量（暂不支持预览）', "EN": 'Quaternion W component (preview not supported yet)'},
    'props.interp.linear': {"ZH": '0 线性 (Linear)', "EN": '0 Linear'},
    'props.interp.linear_desc': {"ZH": '每段是直线', "EN": 'Each segment is a straight line'},
    'props.interp.slow': {"ZH": '1 缓入 (Slow)', "EN": '1 Slow (ease in)'},
    'props.interp.slow_desc': {"ZH": '每段先慢后快，t³', "EN": 'Each segment starts slow and ends fast, t³'},
    'props.interp.fast': {"ZH": '2 缓出 (Fast)', "EN": '2 Fast (ease out)'},
    'props.interp.fast_desc': {"ZH": '每段先快后慢，1−(1−t)³', "EN": 'Each segment starts fast and ends slow, 1−(1−t)³'},
    'props.interp.smooth': {"ZH": '3 缓入缓出 (Smooth)', "EN": '3 Smooth (ease in-out)'},
    'props.interp.smooth_desc': {"ZH": '每段按三次平滑阶跃过渡，段首段尾斜率为 0', "EN": 'Each segment follows a cubic smoothstep; the slope is 0 at both ends'},
    'props.world_up_type.scene_up': {"ZH": '0 世界上方向 (SceneUp)', "EN": '0 SceneUp (world up)'},
    'props.world_up_type.scene_up_desc': {"ZH": '上方向取世界 +Y，上方向向量无效', "EN": 'Up is world +Y; the Up Direction vector is ignored'},
    'props.world_up_type.object_up': {"ZH": '1 辅助骨位置 (ObjectUp)', "EN": '1 ObjectUp (helper bone position)'},
    'props.world_up_type.object_up_desc': {"ZH": '上方向取自己指向辅助骨的方向', "EN": 'Up is the direction from itself to the helper bone'},
    'props.world_up_type.object_rotation_up': {"ZH": '2 辅助骨轴 (ObjectRotationUp)', "EN": '2 ObjectRotationUp (helper bone axis)'},
    'props.world_up_type.object_rotation_up_desc': {"ZH": '上方向取辅助骨的一根局部轴，由「上方向」向量选（(0,1,0) 是 Y，(0,0,1) 是 Z）', "EN": 'Up is one local axis of the helper bone, chosen by the "Up Direction" vector ((0,1,0) is Y, (0,0,1) is Z)'},
    'props.world_up_type.vector': {"ZH": '3 指定上方向 (Vector)', "EN": '3 Vector (explicit up)'},
    'props.world_up_type.vector_desc': {"ZH": '上方向取「上方向」向量给出的世界方向', "EN": 'Up is the world direction given by the "Up Direction" vector'},
    'props.world_up_type.none': {"ZH": '4 最短弧 (None)', "EN": '4 None (shortest arc)'},
    'props.world_up_type.none_desc': {"ZH": '从静止姿态朝目标转最短弧，不约束翻滚', "EN": 'Turns the shortest arc from the rest pose toward the target; roll is not constrained'},
    'props.world_up_type.none_maya_like': {"ZH": '5 父骨最短弧 (None_MayaLike)', "EN": '5 None_MayaLike (parent shortest arc)'},
    'props.world_up_type.none_maya_like_desc': {"ZH": '从父骨朝向起朝目标转最短弧，丢掉静止姿态', "EN": "Turns the shortest arc from the parent bone's orientation toward the target; the rest pose is dropped"},
    'props.rot_rest.replace': {"ZH": '替换', "EN": 'Replace'},
    'props.rot_rest.replace_desc': {"ZH": '结果不含静止姿态（字节 0）', "EN": 'The result excludes the rest pose (byte 0)'},
    'props.rot_rest.add_rest': {"ZH": '叠在静止姿态上', "EN": 'Add to rest pose'},
    'props.rot_rest.add_rest_desc': {"ZH": '结果 = 静止姿态 · 值（字节 48）', "EN": 'Result = rest pose · value (byte 48)'},
    'props.transform.t0': {"ZH": '0：驱动骨骼位置', "EN": '0: drives bone position'},
    'props.transform.t1': {"ZH": '1：欧拉旋转，静止姿态 · Rz·Ry·Rx', "EN": '1: Euler rotation, rest pose · Rz·Ry·Rx'},
    'props.transform.t2': {"ZH": '2：驱动骨骼缩放', "EN": '2: drives bone scale'},
    'props.transform.t3': {"ZH": '3：驱动形变权重', "EN": '3: drives blend shape weight'},
    'props.transform.t4': {"ZH": '4：摆动·扭转旋转，X 为扭转、Y/Z 为摆动。常用于扭转骨、三角肌', "EN": '4: swing-twist rotation; X is twist, Y/Z are swing. Common on twist bones and deltoids'},
    'props.transform.t5': {"ZH": '5：扭转·摆动旋转，与 4 相同但先摆动后扭转', "EN": '5: twist-swing rotation; same as 4 but swing first, then twist'},
    'props.transform.t6': {"ZH": '6：旋转向量，三个分量组成「转轴 × 角度」。常用于 ThighRX/RZ', "EN": '6: rotation vector; the three components form "axis × angle". Common on ThighRX/RZ'},
    'props.transform.t7': {"ZH": '7：可能驱动材质颜色参数', "EN": '7: may drive a material color parameter'},
    'props.transform.t8': {"ZH": '8：可能驱动材质四维参数', "EN": '8: may drive a material 4D parameter'},
    'props.transform.t9': {"ZH": '9：可能驱动材质三维参数', "EN": '9: may drive a material 3D parameter'},
    'props.transform.t10': {"ZH": '10：可能驱动材质二维参数', "EN": '10: may drive a material 2D parameter'},
    'props.transform.t11': {"ZH": '11：可能驱动标量参数', "EN": '11: may drive a scalar parameter'},
    'props.transform.t12': {"ZH": '12：具体作用未知', "EN": '12: purpose unknown'},
    'props.transform.t13': {"ZH": '13：单轴旋转，绕所写的轴；每根骨只有骨上最后一条 13/14 条目生效，常用于辅助骨、布料偏移骨', "EN": '13: single-axis rotation around the written axis; only the last 13/14 entry on a bone takes effect. Common on helper bones and cloth offset bones'},
    'props.transform.t14': {"ZH": '14：与 13 行为相同，两者的区别未知。常用于围裙、触手', "EN": '14: behaves the same as 13; the difference between them is unknown. Common on aprons and tentacles'},
    'props.transform.t15': {"ZH": '15：具体作用未知', "EN": '15: purpose unknown'},
    'props.transform.t16': {"ZH": '16：具体作用未知', "EN": '16: purpose unknown'},
    'props.cm_key.flag_desc': {"ZH": '具体作用未知，改动不影响曲线。常见值为 0、2、5、8', "EN": 'Purpose unknown; changing it does not affect the curve. Common values are 0, 2, 5, 8'},
    'props.cone.index_desc': {"ZH": 'ConeInput 表里的序号', "EN": 'Index in the ConeInput table'},
    'props.cone.value': {"ZH": '输出值', "EN": 'Output Value'},
    'props.cone.value_desc': {"ZH": '这个锥形对应的目标值：角度，缩放目标时为倍数', "EN": 'Target value for this cone: an angle, or a factor for scale targets'},
    'props.int_item.value': {"ZH": '值', "EN": 'Value'},
    'props.hash_item.hash': {"ZH": '哈希', "EN": 'Hash'},
    'props.hash_item.hash_desc': {"ZH": '按有符号整数显示', "EN": 'Shown as a signed integer'},
    'props.hash_item.name': {"ZH": '名称', "EN": 'Name'},
    'props.weighted.bone': {"ZH": '骨骼', "EN": 'Bone'},
    'props.weighted.weight': {"ZH": '权重', "EN": 'Weight'},
    'props.common.driver': {"ZH": '驱动', "EN": 'Driver'},
    'props.source.bone_desc': {"ZH": '被读取的驱动骨骼，可输入以搜索本文件哈希表里的骨骼名', "EN": "The bone being read; type to search bone names in this file's hash table"},
    'props.source.axis': {"ZH": '驱动局部轴向', "EN": 'Driver Local Axis'},
    'props.source.axis_desc': {"ZH": '读取驱动的哪个局部轴，在骨骼自身的局部坐标系里，不是全局坐标系', "EN": "Which local axis of the driver is read, in the bone's own local coordinates, not global"},
    'props.source.from_start': {"ZH": 'From 起点', "EN": 'From Start'},
    'props.source.from_start_desc': {"ZH": '起点 A 的输入，即驱动的读数，单位随读取方式：度、厘米或倍数', "EN": 'Input at start point A, i.e. the driver reading; the unit follows the read mode: degrees, centimeters or factor'},
    'props.source.from_kink': {"ZH": 'From 折点', "EN": 'From Kink'},
    'props.source.from_kink_desc': {"ZH": '折点 B 的输入，两段在这里分界；不启用折点时忽略，落在起点与终点之外时整个驱动失效', "EN": 'Input at kink B, where the two segments meet; ignored when the kink is off; the whole driver is disabled if it lies outside start-end'},
    'props.source.from_end': {"ZH": 'From 终点', "EN": 'From End'},
    'props.source.from_end_desc': {"ZH": '终点 C 的输入', "EN": 'Input at end point C'},
    'props.source.to_start': {"ZH": 'To 起点', "EN": 'To Start'},
    'props.source.to_start_desc': {"ZH": '起点 A 的输出，单位随变换类型：度、厘米或倍数', "EN": 'Output at start point A; the unit follows the transform type: degrees, centimeters or factor'},
    'props.source.to_kink': {"ZH": 'To 折点', "EN": 'To Kink'},
    'props.source.to_kink_desc': {"ZH": '折点 B 的输出，不启用折点时忽略', "EN": 'Output at kink B; ignored when the kink is off'},
    'props.source.to_end': {"ZH": 'To 终点', "EN": 'To End'},
    'props.source.to_end_desc': {"ZH": '终点 C 的输出', "EN": 'Output at end point C'},
    'props.source.ref_frame_x': {"ZH": '参考系 X', "EN": 'Reference Frame X'},
    'props.source.ref_frame_y': {"ZH": '参考系 Y', "EN": 'Reference Frame Y'},
    'props.source.ref_frame_z': {"ZH": '参考系 Z', "EN": 'Reference Frame Z'},
    'props.source.ref_frame_w': {"ZH": '参考系 W', "EN": 'Reference Frame W'},
    'props.source.mid_point': {"ZH": '启用折点 (MidPoint)', "EN": 'Mid Point'},
    'props.source.mid_point_desc': {"ZH": '关：起点到终点一条直线；开：经过折点的两段折线（AttrFlags 位1 MidPoint），折点落在起点与终点之外时输出恒为 0', "EN": 'Off: one straight line from start to end. On: a two-segment line through the kink (AttrFlags bit 1, MidPoint); the output is always 0 if the kink lies outside start-end'},
    'props.source.attr_flags_other': {"ZH": '其余标志位', "EN": 'Other AttrFlags Bits'},
    'props.source.attr_flags_other_desc': {"ZH": 'AttrFlags 去掉位1 的其余位：位0 BasePose 对骨骼不起作用，位2 World 只出现在材质目标上，具体作用未知', "EN": 'AttrFlags bits other than bit 1: bit 0 (BasePose) has no effect on bones; bit 2 (World) only appears on material targets, purpose unknown'},
    'props.source.input_type': {"ZH": '读取方式 InputType (+25)', "EN": 'Input Type (+25)'},
    'props.source.input_type_desc': {"ZH": '从驱动读什么：相对父骨的完整变换（含静止姿态和静止偏移），决定取位置、缩放，还是旋转的哪一种分解', "EN": 'What to read from the driver: its full transform relative to the parent bone (including rest pose and rest offset); decides whether position, scale, or which rotation decomposition is taken'},
    'props.source.rot_order': {"ZH": '欧拉顺序 RotOrder (+27)', "EN": 'Rot Order (+27)'},
    'props.source.rot_order_desc': {"ZH": '读取方式为「欧拉角」时的分解顺序，通常跟着驱动骨走：大腿、手多为 YZX，手指为 ZXY，翅膀为 ZYX，其余为 XYZ', "EN": 'Decomposition order when the input type is "Euler angles"; it usually follows the driver bone: thighs and hands mostly YZX, fingers ZXY, wings ZYX, everything else XYZ'},
    'props.source.cm_count': {"ZH": '曲线关键点数', "EN": 'Curve Key Count'},
    'props.source.cm_count_desc': {"ZH": '曲线的关键点数，导出时按曲线重算', "EN": 'Number of curve keys; recomputed from the curve on export'},
    'props.source.unknown_uint16_22': {"ZH": '未知 UInt16 (+22)', "EN": 'Unknown UInt16 (+22)'},
    'props.common.unknown_usually_0': {"ZH": '具体作用未知。通常为 0', "EN": 'Purpose unknown. Usually 0'},
    'props.source.interpolation': {"ZH": '插值', "EN": 'Interpolation'},
    'props.source.interpolation_desc': {"ZH": '每段映射的过渡方式（+28）：0 线性，3 缓入缓出，1 和 2 极少见', "EN": 'How each mapping segment transitions (+28): 0 linear, 3 ease in-out; 1 and 2 are rare'},
    'props.source.cm_flag': {"ZH": '曲线标记 (+29)', "EN": 'Curve Flag (+29)'},
    'props.source.cm_flag_desc': {"ZH": '有曲线时为 1，导出时自动设置；材质目标上可能为 2', "EN": '1 when there is a curve, set automatically on export; may be 2 on material targets'},
    'props.cns.target_bone': {"ZH": '被驱动', "EN": 'Driven'},
    'props.cns.target_bone_desc': {"ZH": '被驱动的骨骼，可输入以搜索本文件哈希表里的骨骼名', "EN": "The driven bone; type to search bone names in this file's hash table"},
    'props.cns.transform_element': {"ZH": '变换类型 TransformElement', "EN": 'Transform Element'},
    'props.cns.transform_element_desc': {"ZH": '约束驱动的是旋转、平移还是缩放等', "EN": 'Whether the constraint drives rotation, translation, scale, etc.'},
    'props.cns.target_axis': {"ZH": '被驱动局部轴向', "EN": 'Driven Local Axis'},
    'props.cns.target_axis_desc': {"ZH": '驱动被驱动的哪个局部轴，在骨骼自身的局部坐标系里，不是全局坐标系', "EN": "Which local axis of the driven bone is driven, in the bone's own local coordinates, not global"},
    'props.cns.base_pose': {"ZH": '叠加 (BasePose)', "EN": 'Base Pose'},
    'props.cns.base_pose_desc': {"ZH": 'AttrFlags 位0 BasePose。开：值叠加在静止姿态上；关：替换所写的轴（旋转、平移），对缩放不起作用', "EN": 'AttrFlags bit 0 (BasePose). On: the value is added on top of the rest pose; off: replaces the written axis (rotation, translation); no effect on scale'},
    'props.cns.attr_flags_other': {"ZH": '其余标志位', "EN": 'Other Flag Bits'},
    'props.cns.attr_flags_other_desc': {"ZH": 'AttrFlags 去掉位0 的其余位：位4 OutJoint 目标是骨骼、位5 OutRot 目标是旋转（v36/v102 导出时按变换类型重算）；位1 World、位2 ClampMin、位3 ClampMax，位2、位3 只出现在形变和材质目标上', "EN": 'AttrFlags bits other than bit 0: bit 4 OutJoint = target is a bone, bit 5 OutRot = target is a rotation (recomputed from the transform element on v36/v102 export); bit 1 World, bit 2 ClampMin, bit 3 ClampMax, bits 2 and 3 only appear on blend shape and material targets'},
    'props.cns.vec4_zero_desc': {"ZH": '固定为 0，请勿修改', "EN": 'Always 0, do not change'},
    'props.cns.vec4_one_desc': {"ZH": '固定为 1，请勿修改', "EN": 'Always 1, do not change'},
    'props.cns.unknown_byte_72': {"ZH": '未知字节 (+72)', "EN": 'Unknown Byte (+72)'},
    'props.cns.unknown_byte_72_desc': {"ZH": '具体作用未知。通常为 0（约 99%）', "EN": 'Purpose unknown. Usually 0 (about 99%)'},
    'props.cns.target_property': {"ZH": '目标属性', "EN": 'Target Property'},
    'props.cns.target_property_desc': {"ZH": '被驱动的属性名，如材质参数名。只有材质、标量类变换用到，骨骼目标留空', "EN": 'Name of the driven property, e.g. a material parameter name. Only used by material and scalar transforms; leave empty for bone targets'},
    'props.cns.property_hash': {"ZH": '属性哈希覆盖', "EN": 'Property Hash Override'},
    'props.cns.property_hash_desc': {"ZH": '按有符号整数显示，0 表示用目标属性名的哈希，只有属性名对不上哈希时才需要填', "EN": 'Shown as a signed integer; 0 uses the hash of the target property name; only needed when the name does not match the hash'},
    'props.cns.object_hash': {"ZH": '目标哈希覆盖', "EN": 'Target Hash Override'},
    'props.cns.object_hash_desc': {"ZH": '只用于按哈希指定的目标（形变、材质、标量、命名输出），按有符号整数显示，0 表示用目标名的哈希，只有名字对不上哈希时才需要填', "EN": 'Only for targets specified by hash (blend shape, material, scalar, named output); shown as a signed integer; 0 uses the hash of the target name; only needed when the name does not match the hash'},
    'props.cns.unknown_byte_74_desc': {"ZH": '具体作用未知。通常为 0（约 99%），跟着被驱动骨走', "EN": 'Purpose unknown. Usually 0 (about 99%); follows the driven bone'},
    'props.cns.unknown_byte_75_desc': {"ZH": '具体作用未知。通常为 2（约 69%），同一文件里同一变换类型一般只用一个值', "EN": 'Purpose unknown. Usually 2 (about 69%); within one file a transform type normally uses a single value'},
    'props.cns.group_count': {"ZH": '关节组计数', "EN": 'Joint Group Count'},
    'props.cns.group_count_desc': {"ZH": '紧跟在这条后面、与它同目标同变换同 AttrFlags 的连续条目数（组首填 N，组员填 0），导出时自动校验', "EN": "Number of consecutive entries right after this one with the same target, transform and AttrFlags (N on the group's first entry, 0 on the others); validated on export"},
    'props.cns.reserved_tail': {"ZH": '保留字节 +76 / +78 / +79', "EN": 'Reserved Bytes +76 / +78 / +79'},
    'props.cns.reserved_tail_desc': {"ZH": '固定为 0', "EN": 'Always 0'},
    'props.cns.mat_name_hash_desc': {"ZH": '材质名的哈希，十六进制，例如 0x1A2B3C4D', "EN": 'Hash of the material name, hexadecimal, e.g. 0x1A2B3C4D'},
    'props.cns.mat_property_hash_desc': {"ZH": '材质属性名的哈希，十六进制', "EN": 'Hash of the material property name, hexadecimal'},
    'props.cns.mat_name': {"ZH": '材质名', "EN": 'Material Name'},
    'props.cns.mat_name_desc': {"ZH": '模型 mdf2 里的材质名，区分大小写；填了就自动算出材质名哈希', "EN": "The material's name in the model's mdf2, case-sensitive; filling it in computes the material name hash"},
    'props.cns.mat_property': {"ZH": '参数名', "EN": 'Parameter Name'},
    'props.mat.components': {"ZH": '%d 个分量', "EN": '%d components'},
    'props.mdf_ref.filepath': {"ZH": 'mdf2 文件', "EN": 'mdf2 File'},
    'props.mdf_ref.filepath_desc': {"ZH": '提供材质名和参数名的 .mdf2 文件', "EN": 'The .mdf2 file the material and parameter names come from'},
    'props.cns.mat_property_desc': {"ZH": '该材质在 mdf2 里的参数名，区分大小写；填了就自动算出参数名哈希', "EN": "The material parameter's name in the mdf2, case-sensitive; filling it in computes the parameter hash"},
    'props.cns.mat_apply_mode': {"ZH": '写入方式 (ApplyMode)', "EN": 'Apply Mode'},
    'props.cns.mat_apply_mode_desc': {"ZH": '骨骼的哪种量写进材质参数', "EN": 'Which quantity of the bone goes into the material parameter'},
    'props.mat_apply.trans': {"ZH": '0 位置 (Trans)', "EN": '0 Trans'},
    'props.mat_apply.trans_desc': {"ZH": '骨骼位置，常配 *_Pos、*_Start 参数', "EN": 'Bone position; usually paired with *_Pos and *_Start parameters'},
    'props.mat_apply.euler': {"ZH": '1 欧拉角 (Euler)', "EN": '1 Euler'},
    'props.mat_apply.euler_desc': {"ZH": '骨骼的欧拉角，具体作用未知', "EN": 'Bone Euler angles; purpose unknown'},
    'props.mat_apply.scale': {"ZH": '2 缩放 (Scale)', "EN": '2 Scale'},
    'props.mat_apply.scale_desc': {"ZH": '骨骼缩放，常配 *_Scale 参数', "EN": 'Bone scale; usually paired with *_Scale parameters'},
    'props.mat_apply.rot': {"ZH": '3 旋转 (Rot)', "EN": '3 Rot'},
    'props.mat_apply.rot_desc': {"ZH": '骨骼旋转，具体作用未知', "EN": 'Bone rotation; purpose unknown'},
    'props.cns.multi_tail': {"ZH": '尾部 2 字节', "EN": 'Tail 2 Bytes'},
    'props.cns.multi_tail_desc': {"ZH": '记录尾部第 2、3 字节：v102 固定为 0，RE9（v35）逐条不同，新建条目取本文件最常见的值', "EN": 'Bytes 2 and 3 of the record tail: always 0 on v102, differs per entry on RE9 (v35); a new entry takes the most common value in this file'},
    'props.cns.aim_target_bone': {"ZH": '瞄准目标', "EN": 'Aim Target'},
    'props.cns.aim_up_bone': {"ZH": '辅助骨骼', "EN": 'Helper Bone'},
    'props.cns.aim_up_bone_desc': {"ZH": '辅助骨骼（AimVectorPointJoint），留空表示不使用', "EN": 'Helper bone (AimVectorPointJoint); leave empty to not use one'},
    'props.cns.aim_influence': {"ZH": '影响', "EN": 'Influence'},
    'props.cns.aim_offset': {"ZH": '旋转偏移', "EN": 'Rotation Offset'},
    'props.cns.aim_offset_desc': {"ZH": 'XYZ 欧拉角（弧度），右乘在瞄准结果后面，让本地瞄准轴偏离目标；只有类型 2 用到', "EN": 'XYZ Euler angles (radians), right-multiplied after the aim result so the local aim axis deviates from the target; only used by type 2'},
    'props.cns.aim_axis': {"ZH": '瞄准轴', "EN": 'Aim Axis'},
    'props.cns.aim_axis_desc': {"ZH": '被驱动自己的局部轴，指向瞄准目标', "EN": "The driven bone's own local axis that points at the aim target"},
    'props.cns.aim_up_axis': {"ZH": '上方向轴', "EN": 'Up Axis'},
    'props.cns.aim_up_axis_desc': {"ZH": '被驱动自己的局部轴，与上方向对齐', "EN": "The driven bone's own local axis aligned with the up direction"},
    'props.cns.aim_up_dir': {"ZH": '上方向', "EN": 'Up Direction'},
    'props.cns.aim_up_dir_desc': {"ZH": '类型 3 下是世界里的上方向；类型 2 下选辅助骨的哪根局部轴；类型 0 无效', "EN": 'Type 3: the up direction in world space; type 2: which local axis of the helper bone; type 0: ignored'},
    'props.cns.world_up_type': {"ZH": '类型', "EN": 'Type'},
    'props.cns.aim_bytes': {"ZH": '字节 +57..59', "EN": 'Bytes +57..59'},
    'props.cns.rot_rest_mode': {"ZH": '静止姿态', "EN": 'Rest Pose'},
    'props.cns.rot_unknown_bytes': {"ZH": '未知字节 0 / 2 / 3', "EN": 'Unknown Bytes 0 / 2 / 3'},
    'props.cns.rot_gains': {"ZH": '系数', "EN": 'Gains'},
    'props.cns.rot_gains_desc': {"ZH": '每轴的系数。(1,1,1) 是精确拷贝；其他值小角度时每轴相乘，大角度偏离线性', "EN": 'Per-axis gain. (1,1,1) is an exact copy; other values multiply per axis at small angles and deviate from linear at large angles'},
    'props.cns.preview_on': {"ZH": '已应用预览', "EN": 'Preview Applied'},
    'props.cns.preview_on_desc': {"ZH": '此条目是否已在骨架上应用预览', "EN": 'Whether a preview of this entry is applied on the armature'},
    'props.root.sdk_driver_bone_desc': {"ZH": '烘焙约束里被读取的骨骼', "EN": 'The bone read in the baked constraint'},
    'props.root.source_filepath': {"ZH": '源文件', "EN": 'Source File'},
    'props.root.source_filepath_desc': {"ZH": '原始 .jcns 文件的绝对路径', "EN": 'Absolute path of the original .jcns file'},
    'props.root.jxg_path': {"ZH": 'JXG 路径', "EN": 'JXG Path'},
    'props.root.jxg_path_desc': {"ZH": '表达式图（JointExprGraph）资源的路径；留空表示文件没有 JXG', "EN": 'Path of the expression graph (JointExprGraph) resource; empty means the file has no JXG'},
    'props.root.target_armature': {"ZH": '目标骨架', "EN": 'Target Armature'},
    'props.root.target_armature_desc': {"ZH": '约束要作用到的骨架', "EN": 'The armature the constraints act on'},
    'props.root.header_unknown_bytes': {"ZH": '文件头未知字节', "EN": 'Header Unknown Bytes'},
    'props.root.header_unknown_bytes_desc': {"ZH": '文件头里 SectionCount 之后的两个标志字节，取值 0 或 1，具体作用未知', "EN": 'The two flag bytes after SectionCount in the file header, value 0 or 1, purpose unknown'},
    'props.root.source_version': {"ZH": 'JCNS 版本', "EN": 'JCNS Version'},
    'props.root.browser_kind': {"ZH": '分区', "EN": 'Section'},
    'props.root.browser_kind_desc': {"ZH": '在列表里显示哪一类条目', "EN": 'Which kind of entry the list shows'},
    'props.root.browser_view': {"ZH": '视图', "EN": 'View'},
    'props.root.browser_view_desc': {"ZH": 'Outputs 条目按条目排列，或按被驱动的骨骼分组', "EN": 'Outputs entries listed one by one, or grouped by driven bone'},
    'props.root.view_entry': {"ZH": '按条目', "EN": 'By Entry'},
    'props.root.view_entry_desc': {"ZH": '按文件顺序列出条目', "EN": 'List entries in file order'},
    'props.root.view_bone': {"ZH": '按骨骼', "EN": 'By Bone'},
    'props.root.view_bone_desc': {"ZH": '按被驱动的骨骼分组，列出每个通道和上面的条目', "EN": 'Group by driven bone, listing each channel and the entries on it'},
    'props.root.entry_index': {"ZH": '条目', "EN": 'Entry'},
    'props.root.entry_index_desc': {"ZH": '列表里当前条目的序号；读写的是当前活动物体', "EN": 'Index of the current entry in the list; reads and writes the active object'},
    'props.root.rot_map_value': {"ZH": 'RotExpr 映射值', "EN": 'RotExpr Map Value'},
    'props.root.rot_map_value_desc': {"ZH": '每条 RotExpr 条目共用的映射常量，新增条目沿用；具体作用未知', "EN": 'Mapping constant shared by every RotExpr entry; new entries reuse it; purpose unknown'},
    'props.root.detected_game': {"ZH": '游戏', "EN": 'Game'},
    'props.root.game_wilds': {"ZH": '怪物猎人荒野 (v102)', "EN": 'Monster Hunter Wilds (v102)'},
    'props.root.game_wilds_desc': {"ZH": 'Monster Hunter Wilds TU4 之后', "EN": 'Monster Hunter Wilds, after TU4'},
    'props.root.game_re9': {"ZH": '生化危机9 / PRAGMATA (v35)', "EN": 'Resident Evil 9 / PRAGMATA (v35)'},
    'props.scene.active_collection': {"ZH": '工作集合', "EN": 'Working Collection'},
    'props.scene.active_collection_desc': {"ZH": '导出等操作默认作用的 JCNS 集合。留空则改用当前选中的物体', "EN": 'The JCNS collection that operations like export act on by default. If empty, the selected object is used'},
    'props.euler.order_desc': {"ZH": 'Blender 的 %s 顺序（%s 轴最先作用）', "EN": "Blender's %s order (the %s axis is applied first)"},
}
